### ISSUE TITLE
Postgres Existing Secret

### ISSUE THREAD

**Issue by pagey101** [bootc/netbox-chart#109]
Hello

I am trying to keep the Postgres password in an existing secret, however it is not at all clear how to do this.

I have tried the following:

```
postgresql:
  auth:
    existingSecret: database-passwords
    userPasswordKey: user_password
```

However, I have no idea how to tell Netbox what the password is.

I am using chart version 4.0.1.

Appreciate any help.

Thanks

**Comment by rjhenry** [comment]
To clarify, are you using an *external* Postgres instance, or the bundled subchart? If the former, you'll want to set things up with the `externalDatabase` key, similar to the following:
```yaml
externalDatabase:                                                           
  host: <redacted>
  port: 5432
  database: netbox
  username: netbox
  existingSecretName: netbox-postgres
  existingSecretKey: password
```
If you're planning on using this for any kind of production use it's strongly recommended to manage the PostgresQL database separately, e.g on a separate host or with the Zalando operator.
 
If you're choosing to use the bundled Postgres chart, Netbox should pull the value of the password from the Postgres chart's secret, if I'm reading the manifests correctly, referencing [the deployment](https://github.com/bootc/netbox-chart/blob/develop/templates/deployment.yaml#L178), and the helpers defined [here](https://github.com/bootc/netbox-chart/blob/develop/templates/_helpers.tpl#L30) and [here](https://github.com/bootc/netbox-chart/blob/develop/templates/_helpers.tpl#L93).

If that's not working, I'd be useful to see the resultant `volumes` section of the deployment.

**Comment by pagey101** [comment]
Thanks for the quick response. I am using the bundled Postgres chart.

I've used these values now, after inspecting the inner workings of the chart/s:

```
postgresql:
  enabled: true
  existingSecret: database-passwords
  secretKey: postgresql-postgres-password
```

Which enabled Postgres to start properly, however I get the following from Netbox:

```
MountVolume.SetUp failed for volume "secrets" : secret "netbox-postgresql" not found
```

Looking at the helpers:

```
{{- define "netbox.postgresql.secret" -}}
{{- if and .Values.postgresql.enabled .Values.postgresql.existingSecret -}}
{{ .Values.postgresql.existingSecret }}
```

This should mean that as long as postgres.enabled, and postgresql.existingSecret are defined, then the secret name should be the postgresql.existingSecret. However, I see the secret is generated as below (netbox-postgresql), which does not match the name I gave:

```
          - secret:
              items:
              - key: postgresql-password
                path: db_password
              name: netbox-postgresql
```

Any ideas?

Thanks

**Comment by rjhenry** [comment]
The Helm chart checks for `postgresql.existingSecret`, but requires `postgresql.auth.existingSecret` to pass credentials into Postgres, which I think is where things are getting confused. I think what's needed is to update the Helm chart check for `postgresql.auth.existingSecret`, like so:
```diff
diff --git a/templates/_helpers.tpl b/templates/_helpers.tpl
index ec5186b..50b4c55 100644
--- a/templates/_helpers.tpl
+++ b/templates/_helpers.tpl
@@ -91,8 +91,8 @@ Create the name of the service account to use
 Name of the Secret that contains the PostgreSQL password
 */}}
 {{- define "netbox.postgresql.secret" -}}
-{{- if and .Values.postgresql.enabled .Values.postgresql.existingSecret -}}
-{{ .Values.postgresql.existingSecret }}
+{{- if and .Values.postgresql.enabled .Values.postgresql.auth.existingSecret -}}
+{{ .Values.postgresql.auth.existingSecret }}
 {{- else if .Values.postgresql.enabled -}}
 {{ include "netbox.postgresql.fullname" . }}
 {{- else if .Values.externalDatabase.existingSecretName -}}
```

I'll draft a PR and test when I've got a few more minutes to spare, unless someone beats me to it!

**Comment by bootc** [comment]
Thanks for debugging this @rjhenry that seems sensible...

**Comment by pagey101** [comment]
Hmm I'm not sure, correct me if wrong. If the mentioned fix would work then the below values should work?

```
postgresql:
  enabled: true
  auth:
    existingSecret: database-passwords
  existingSecret: database-passwords
  secretKey: postgresql-postgres-password
```

However, I get the same results.

Thanks

**Comment by pagey101** [comment]
I've done some further investigation and found that the line below does not work (the existingSecret is not used when both postgresql.enabled and Postgres.existingSecret are defined):

```
{{- if and .Values.postgresql.enabled .Values.postgresql.existingSecret -}}
```

Here is my fix suggestion (similar to how Redis is handled):

```diff
diff --git a/templates/_helpers.tpl b/templates/_helpers.tpl
index ec5186b..05c0804 100644
--- a/templates/_helpers.tpl
+++ b/templates/_helpers.tpl
@@ -91,15 +91,17 @@ Create the name of the service account to use
 Name of the Secret that contains the PostgreSQL password
 */}}
 {{- define "netbox.postgresql.secret" -}}
-{{- if and .Values.postgresql.enabled .Values.postgresql.existingSecret -}}
-{{ .Values.postgresql.existingSecret }}
-{{- else if .Values.postgresql.enabled -}}
-{{ include "netbox.postgresql.fullname" . }}
-{{- else if .Values.externalDatabase.existingSecretName -}}
-{{ .Values.externalDatabase.existingSecretName }}
-{{- else -}}
-{{ .Values.existingSecret | default (include "netbox.fullname" .) }}
-{{- end -}}
+  {{- if .Values.postgresql.enabled -}}
+    {{- if .Values.postgresql.existingSecret -}}
+      {{- .Values.postgresql.existingSecret }}
+    {{- else }}
+      {{ include "netbox.postgresql.fullname" . }}
+    {{- end }}
+  {{- else if .Values.externalDatabase.existingSecretName -}}
+    {{- .Values.externalDatabase.existingSecretName }}
+  {{- else -}}
+    {{ .Values.existingSecret | default (include "netbox.fullname" .) }}
+  {{- end -}}
 {{- end }}
 
 {{/*
```

However, I am now getting the below from netbox:

```
settings.DATABASES is improperly configured. Please supply the NAME or OPTIONS['service'] value
```

Thanks

**Comment by pagey101** [comment]
I finally have this working with my above patch and the following values:

```
postgresql:
  enabled: true
  postgresqlUsername: netbox
  postgresqlDatabase: netbox
  existingSecret: database-passwords
```
