### ISSUE TITLE
Adding modules to netbox

### ISSUE THREAD

**Issue by 20012455** [bootc/netbox-chart#118]
Hello, 

I would like to install modules using pip to enable SSO/SAML authentication on netbox. (django3_saml2_nbplugin)

**REMOTE_AUTH_BACKEND: 'django3_saml2_nbplugin.backends.SAML2CustomAttrUserBackend'**

But, I can't figure where can I install modules ? I've looked on all the files and I can't find anything with **pip**, I understood I need to create on the chart to do it myself, but anyone has done this on this chart before ?

Thanks

**Comment by 20012455** [comment]
Update: 
As found on netbox documentation:
`Once installed, add the package to local_requirements.txt to ensure it is re-installed during future rebuilds of the virtual environment`

So, what I've tried: 
**configmap.yaml**
```yaml
data:
  local_requirements.txt: |
    netbox-bgp
```
**deployment.yaml**
```yaml
          volumeMounts:
            - name: config
              mountPath: /etc/netbox/config/configuration.py
              subPath: configuration.py
              readOnly: true
            - name: requirements
              mountPath: /opt/netbox/local_requirements.txt
              subPath: local_requirements.txt
```
```yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "netbox.fullname" . }}
        - name: requirements
          configMap:
            name: {{ include "netbox.fullname" . }}
```

I can see the file within /opt/netbox, but:
```shell
I have no name!@netbox-lr8-5cdcfc8fc9-p5lfn:/opt/netbox$ source venv/bin/activate
(venv) I have no name!@netbox-lr8-5cdcfc8fc9-p5lfn:/opt/netbox$ pip list | grep netbox
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: pip install --upgrade pip
(venv) I have no name!@netbox-lr8-5cdcfc8fc9-p5lfn:/opt/netbox$ pip install -r local_requirements.txt 
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting netbox-bgp
  Downloading netbox_bgp-0.8.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 kB 2.3 MB/s eta 0:00:00
Installing collected packages: netbox-bgp
ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/opt/netbox/venv/lib/python3.10/site-packages/netbox_bgp'


[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: pip install --upgrade pip
(venv) I have no name!@netbox-lr8-5cdcfc8fc9-p5lfn:/opt/netbox$ 
```
Package is not installed when the pod is creating

It seems that:

  1. Volume is read-only ?
  2. No permissions for this user
