### ISSUE TITLE
Default SubCharts

### ISSUE THREAD

**Issue by fadecore** [bootc/netbox-chart#121]
As also mentioned in https://github.com/bootc/netbox-chart/issues/117 I want to discuss the defaults of the helm chart.  

# Current situation:  

## Chart.yaml
```
dependencies:
- name: postgresql
  version: 10.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 15.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
```
**postgresql:** 
- regarding https://endoflife.date/postgresql even for the latest 10.23 support ended today 
- when you take the default settings in private environments where https://charts.bitnami.com/bitnami can not be reached it takes the /charts/postgresl/Chart.yaml that comes with the [chart.tgz](https://charts.boo.tc/charts/netbox-4.1.1.tgz) (not included as code in this repo). This version is then a 10.14, which is even older

**redis:**
- nearly same, but should be handled the same :)

## README.md
The readme says to use the standalone chart from upstream provider instead of the included charts - true, but ...

# Problem Statement:
- Security starts from the beginning with "secure" defaults to prevent data breaches.
- It would also help to get a better security rating on https://artifacthub.io/packages/helm/bootc/netbox 

# Proposal:
- [ ] Update dependencies version in Chart.yaml
- [ ] don't know in which step you add the files of the dependency charts, there is most probably a Chart.lock that also should be updated  somewhere
- [ ] I will create a PR
