### ISSUE TITLE
Redis ResponseError: WRONGPASS invalid username-password pair or user is disabled

### ISSUE THREAD

**Issue by Norkl** [bootc/netbox-chart#127]
Hello,

Tried deploying Netbox on OpenShift/OKD environment. At first it runs as expected, however after some time I'm getting `Redis ResponseError: WRONGPASS invalid username-password pair or user is disabled` error message.
It's an intermittent error that shows up randomly. It can be running for several days before the error starts spamming, other times it can take one hour before the error shows up. 

Any idea what I'm missing here? 

OpenShift/OKD version: `4.11` 
Kubernetes version: `1.24`

Error when accessing the Netbox webui:
![image](https://user-images.githubusercontent.com/11365241/207368058-26ea6a48-d86b-4d8f-b845-e26adfe84a37.png)

Here is the error in full:
```
netbox-86d647544d-zl897 netbox During handling of the above exception, another exception occurred:                                                                                                                                                                                                                             
netbox-86d647544d-zl897 netbox                                                                                                                                                                                                                                                                                                 
netbox-86d647544d-zl897 netbox Traceback (most recent call last):                                                                                                                                                                                                                                                              
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner                                                                                                                                                                                     
netbox-86d647544d-zl897 netbox     response = get_response(request)                                                                                                                                                                                                                                                            
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response                                                                                                                                                                                 
netbox-86d647544d-zl897 netbox     response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                                                                                                                                                                     
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view                                                                                                                                                                                           
netbox-86d647544d-zl897 netbox     return self.dispatch(request, *args, **kwargs)                                                                                                                                                                                                                                              
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper                                                                                                                                                                                         
netbox-86d647544d-zl897 netbox     return bound_method(*args, **kwargs)                                                                                                                                                                                                                                                        
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper                                                                                                                                                          
netbox-86d647544d-zl897 netbox     return view(request, *args, **kwargs)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/netbox/users/views.py", line 39, in dispatch
netbox-86d647544d-zl897 netbox     return super().dispatch(*args, **kwargs)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
netbox-86d647544d-zl897 netbox     return handler(request, *args, **kwargs)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/netbox/users/views.py", line 52, in get
netbox-86d647544d-zl897 netbox     return render(request, self.template_name, { 
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
netbox-86d647544d-zl897 netbox     content = loader.render_to_string(template_name, context, request, using=using)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
netbox-86d647544d-zl897 netbox     return template.render(context, request)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
netbox-86d647544d-zl897 netbox     return self.template.render(context)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
netbox-86d647544d-zl897 netbox     with context.bind_template(self):
netbox-86d647544d-zl897 netbox   File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
netbox-86d647544d-zl897 netbox     return next(self.gen)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/debug_toolbar/panels/templates/panel.py", line 45, in _request_context_bind_template
netbox-86d647544d-zl897 netbox     context = processor(self.request)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/netbox/netbox/context_processors.py", line 13, in settings_and_registry
netbox-86d647544d-zl897 netbox     'config': get_config(),
netbox-86d647544d-zl897 netbox   File "/opt/netbox/netbox/netbox/config/__init__.py", line 27, in get_config
netbox-86d647544d-zl897 netbox     _thread_locals.config = Config()
netbox-86d647544d-zl897 netbox   File "/opt/netbox/netbox/netbox/config/__init__.py", line 47, in __init__
netbox-86d647544d-zl897 netbox     self._populate_from_cache()
netbox-86d647544d-zl897 netbox   File "/opt/netbox/netbox/netbox/config/__init__.py", line 70, in _populate_from_cache
netbox-86d647544d-zl897 netbox     self.config = cache.get('config') or {}
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/cache.py", line 91, in get
netbox-86d647544d-zl897 netbox     value = self._get(key, default, version, client)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/cache.py", line 38, in _decorator
netbox-86d647544d-zl897 netbox     raise e.__cause__
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/client/default.py", line 258, in get
netbox-86d647544d-zl897 netbox     value = client.get(key)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/commands/core.py", line 1705, in get
netbox-86d647544d-zl897 netbox     return self.execute_command("GET", name)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
netbox-86d647544d-zl897 netbox     conn = self.connection or pool.get_connection(command_name, **options)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
netbox-86d647544d-zl897 netbox     connection.connect()
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 623, in connect
netbox-86d647544d-zl897 netbox     self.on_connect()
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 713, in on_connect
netbox-86d647544d-zl897 netbox     auth_response = self.read_response()
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 839, in read_response
netbox-86d647544d-zl897 netbox     raise response
netbox-86d647544d-zl897 netbox redis.exceptions.ResponseError: WRONGPASS invalid username-password pair or user is disabled.
netbox-86d647544d-zl897 netbox 10.131.2.1 - - [12/Dec/2022:07:08:01 +0000] "GET /login/ HTTP/1.1" 500 1627 "-" "kube-probe/1.24"
netbox-86d647544d-zl897 netbox Internal Server Error: /login/
netbox-86d647544d-zl897 netbox Traceback (most recent call last):
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/cache.py", line 31, in _decorator
netbox-86d647544d-zl897 netbox     return method(self, *args, **kwargs)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/cache.py", line 98, in _get
netbox-86d647544d-zl897 netbox     return self.client.get(key, default=default, version=version, client=client)
netbox-86d647544d-zl897 netbox   File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/client/default.py", line 260, in get
netbox-86d647544d-zl897 netbox     raise ConnectionInterrupted(connection=client) from e
netbox-86d647544d-zl897 netbox django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: WRONGPASS invalid username-password pair or user is disabled.
```

The values overrides I use:
```
  - name: netbox
    type: helm
    repository: https://charts.boo.tc
    chart: netbox
    tag: 4.1.1
    namespace: netbox
    parameters:
      - name: replicaCount
        value: '1'
        forceString: true
      - name: securityContext.runAsUser
        value: '1000920000'
      - name: securityContext.runAsGroup
        value: '1000920000'
      - name: init.securityContext.runAsUser
        value: '1000920000'
      - name: init.securityContext.runAsGroup
        value: '1000920000'
      - name: podSecurityContext.fsGroup
        value: '1000920000'
      - name: worker.securityContext.runAsUser
        value: '1000920000'
      - name: worker.securityContext.runAsGroup
        value: '1000920000'
      - name: worker.podSecurityContext.fsGroup
        value: '1000920000'
      - name: postgresql.enabled
        value: 'false'
      - name: externalDatabase.host
        value: 'netbox-psql-postgresql'
      - name: externalDatabase.existingSecretName
        value: 'netbox-credentials'
      - name: externalDatabase.existingSecretKey
        value: 'password'
      - name: persistence.accessMode
        value: 'ReadWriteMany'
      - name: existingSecret
        value: 'netbox'
      - name: superuser.name
        value: 'netbox'
      - name: housekeeping.securityContext.runAsUser
        value: '1000920000'
      - name: housekeeping.securityContext.runAsGroup
        value: '1000920000'
      - name: housekeeping.podSecurityContext.fsGroup
        value: '1000920000'
      - name: remoteAuth.enabled
        value: 'true'
      - name: remoteAuth.backend
        value: 'netbox.authentication.LDAPBackend'
      - name: remoteAuth.ldap.serverUri
        value: 'ldap://<URL>:389'
      - name: remoteAuth.ldap.startTls
        value: 'false'
      - name: remoteAuth.ldap.ignoreCertErrors
        value: 'true'
      - name: remoteAuth.ldap.bindDn
        value: 'CN=ZZZ,OU=UsersSys,DC=ad,DC=XXX,DC=YY'
      - name: remoteAuth.ldap.bindPassword
        value: ''
      - name: remoteAuth.ldap.userDnTemplate
        value: 'null'
      - name: remoteAuth.ldap.userSearchBaseDn
        value: 'DC=ad,DC=XXX,DC=YY'
      - name: remoteAuth.ldap.userSearchAttr
        value: 'sAMAccountName'
      - name: remoteAuth.ldap.groupSearchBaseDn
        value: 'DC=ad,DC=XXX,DC=YY'
      - name: remoteAuth.ldap.groupSearchClass
        value: 'group'
      - name: remoteAuth.ldap.groupType
        value: 'GroupOfNamesType'
      - name: remoteAuth.ldap.requireGroupDn
        value: 'CN=ZZZ,OU=ZZZ,OU=SysInt,DC=ad,DC=XXX,DC=YY'
      - name: remoteAuth.ldap.findGroupPerms
        value: 'true'
      - name: remoteAuth.ldap.mirrorGroups
        value: 'true'
      - name: remoteAuth.ldap.mirrorGroupsExcept
        value: 'null'
      - name: remoteAuth.ldap.isAdminDn
        value: 'CN=ZZZ,OU=ZZZ,OU=SysInt,DC=ad,DC=XXX,DC=YY'
      - name: remoteAuth.ldap.isSuperUserDn
        value: 'CN=ZZZ,OU=ZZZ,OU=SysInt,DC=ad,DC=XXX,DC=YY'
      - name: remoteAuth.ldap.attrFirstName
        value: 'givenName'
      - name: remoteAuth.ldap.attrLastName
        value: 'sn'
      - name: remoteAuth.ldap.attrMail
        value: 'mail'
      - name: debug
        value: 'true'
```
