### ISSUE TITLE
Deployment Failed when using hostAliases

### ISSUE THREAD

**Issue by riconem** [bootc/netbox-chart#128]
# Description
When you try to use the `hostAliases` in the deployment and worker, the template is not working anymore.

```yaml
# values.yaml
hostAliases:
  - ip: '5.6.7.8'
    hostnames: 
      - 'example1.com'
      - 'example2.com'
  - ip: '1.2.3.4'
    hostnames: 
      - 'example1-ref.com'
      - 'example2-ref.com'
```

# Failure
```
Warning  error   7s (x11 over 50m)    helm-controller  Helm upgrade failed: YAML parse error on netbox/templates/deployment.yaml: error converting YAML to JSON: yaml: line 155: block sequence entries are not allowed in this context
```

# Guess
I have added the the `hostAliases` in #97, but I think there is typo. Because I was using `indent` instead of `nindent`.  See the following.
https://github.com/bootc/netbox-chart/blob/dde8cfd498373499bb4970567904129a0202c397/templates/deployment.yaml#L229
https://github.com/bootc/netbox-chart/blob/dde8cfd498373499bb4970567904129a0202c397/templates/worker-deployment.yaml#L175
