### ISSUE TITLE
expose `FILE_UPLOAD_MAX_MEMORY_SIZE`

### ISSUE THREAD

**Issue by vink78** [bootc/netbox-chart#157]
This new settings was introduced in https://github.com/netbox-community/netbox/issues/11592

It would be great to expose it on helm chart

**Comment by vink78** [comment]
According to `values.yaml`, I can do it with this extra parameter without editing chart:

```yaml
extraConfig:
  - values:
      FILE_UPLOAD_MAX_MEMORY_SIZE: 10000000
```
