### ISSUE TITLE
Bundled postgresql does not survive chart upgrade

### ISSUE THREAD

**Issue by wastrachan** [bootc/netbox-chart#36]
After a chart upgrade, the netbox pod crash-loops with the following output:

```
django.db.utils.OperationalError: FATAL:  password authentication failed for user "netbox"
```

It appears that the default database credentials generated with the bundled chart do not persist upgrade. This can be reproduced by added a noop annotation (or modifying the config map) and running `helm upgrade`

**Comment by wastrachan** [comment]
Issue is no longer present in 7e54108cf37cf7b77d7aaa5fb68d6ea59856135c. The postgres bundled dependency update in 741a664dab9457b3ded38b4a1c6fd3c438eec3f4 is the most likely explanation.

**Comment by bootc** [comment]
Hmm, yes, good catch. Do you have any thoughts about how to avoid this problem? I mean, aside from strongly recommending that an external PostgreSQL instance should be used, I guess...

**Comment by wastrachan** [comment]
I suspect the culprit is https://github.com/bootc/netbox-chart/blob/master/templates/configmap.yaml#L27. 

`postgresql-password` seems like it is randomly generated when bundled chart is rendered (https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/_helpers.tpl#L59), but it is likely only evaluated when the database is initialized on first run. It's ultimately fed in as `POSTGRESQL_PASSWORD` (https://github.com/bitnami/bitnami-docker-postgresql#setting-the-root-password-on-first-run), which "when running the image for the first time will set the password", according to the maintainer.

Given this, the _best_ (read: simplest) course of action (aside from using an external instance, of course), is probably just to set `postgresqlPassword` for the user by default, to prevent the password from auto-generating every time Helm renders the postgres chart. Obviously users should override this password if they're going to use the bundled postgres chart for anything but development purposes.


```
postgresql:
  ## Deploy PostgreSQL using bundled chart
  # To use an external database, set this to false and configure the settings
  # under externalDatabase
  enabled: true

  postgresqlUsername: netbox
  postgresqlPassword: netbox
  postgresqlDatabase: netbox
```
