### ISSUE TITLE
Media Permission denied

### ISSUE THREAD

**Issue by modzilla99** [bootc/netbox-chart#52]
When provisioning the volume with NFS for RWX it will give me the permission denied error since by default the folder will be owned by "nobody".

To mitgate this a init container like this could be added:

```yaml
...
  - name: init-chown
    image: busybox:1.32.1
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - chown -R 1000:1000 /mnt/media
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: false
    volumeMounts:
    - mountPath: /mnt/media
      name: media
...
```
