### ISSUE TITLE
Add additonal remote auth settings

### ISSUE THREAD

**Issue by cstisa** [bootc/netbox-chart#62]
Currently the `remoteAuth` setting contains only the following values :
```
remoteAuth:
  enabled: false
  backend: netbox.authentication.RemoteUserBackend
  header: HTTP_REMOTE_USER
  autoCreateUser: true
  defaultGroups: []
  defaultPermissions: {}
```
It would be nice to add [the rest of settings](https://netbox.readthedocs.io/en/stable/configuration/optional-settings/) for remote auth supported by NetBox, like `REMOTE_AUTH_GROUP_HEADER` or `REMOTE_AUTH_GROUP_SYNC_ENABLED` for example.
