### ISSUE TITLE
Unable to upload image

### ISSUE THREAD

**Issue by stblassitude** [bootc/netbox-chart#63]
I've just freshly deployed netbox through this chart, using these values:
```
postgresql:
  postgresqlPostgresPassword: "tvyc2ZhPt8Pp-3rw"
  postgresqlPassword: "qypKgsUz_-w@.H7a"

ingress:
  enabled: true
  hosts:
    - host: "netbox.app.example.net"
      paths:
        - /

```

I've tried to add a Device Type with two images, and I'm getting this error message:
<img width="854" alt="netbox-image-upload-error" src="https://user-images.githubusercontent.com/202994/141652324-5aeb4ac1-7b9e-4eb7-bb99-49b5342eb9ca.png">

> A file permission error was detected while processing this request. Common causes include the following:
> 
>  Insufficient write permission to the media root - The configured media root is . Ensure that the user NetBox runs as has access to write files to all locations within this path.
> 
> The complete exception is provided below:
> 
> <class 'PermissionError'>
> 
> [Errno 13] Permission denied: '/opt/netbox/netbox/media/devicetype-images'
> 
> Python version: 3.8.7
> NetBox version: 2.10.4
> If further assistance is required, please post to the NetBox mailing list.

For the netbox pod, I'm seeing a volume mount and volume for media:
```
...
    volumeMounts:
...
    - mountPath: /opt/netbox/netbox/media
      name: media
...
  volumes:
...
  - emptyDir:
      medium: Memory
    name: optunit
  - name: media
    persistentVolumeClaim:
      claimName: netbox-media
...
```

The mounted directory is owned by root:
```
$ ls -la /opt/netbox/netbox/media
total 24
drwxr-xr-x    3 root     root          4096 Nov 13 14:15 .
drwxr-xr-x    1 root     root          4096 Feb 18  2021 ..
drwx------    2 root     root         16384 Nov 13 14:15 lost+found
```

The PVC is backed by a longhorn PV. I don't see any options to adjust the permissions of the volume in values.yaml.

**Comment by stblassitude** [comment]
I managed to fix the permissions using these values:
```
podSecurityContext:
  fsGroup: 1000

worker:
  podSecurityContext:
    fsGroup: 1000
```

Since the security context is configured to run netbox as non-root, would it make sense to set these as default in values.yaml, as well?
