### ISSUE TITLE
housekeeping stuck in ContainerCreating mode

### ISSUE THREAD

**Issue by Atoms** [bootc/netbox-chart#70]
When housekeeping and persistence are enabled pods with volumes should be started on the same nodes, at least on GCP, as GCP can mount any from default storage classes only to one node at the same time.
By looking into CronJob template i see that it tries to mount those volumes, but then again, reading https://demo.netbox.dev/static/docs/administration/housekeeping/ documentation housekeeping needs only database access. 

Another possible solution would be to write podAffinity so that cronjob is started on node together with netbox application

**Comment by Atoms** [comment]
Sure, i will start working on this :)

**Comment by Atoms** [comment]
Actually it is same situation with worker pod too.

**Comment by Atoms** [comment]
by working on this, found also, that, if ReadWriteOnce is used, then housekeeping should be disabled, cause CronJob does not have PodAffinity definition

**Comment by bootc** [comment]
There's a `housekeeping.affinity` setting that does what you want I think?

**Comment by Atoms** [comment]
CronJob does not support affinity as per spec: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/

**Comment by bootc** [comment]
CronJob doesn't need to support it, it's not its job. All a CronJob does is create [Jobs](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/) from the `jobTemplate` based on the `schedule`. Similarly, Jobs don't do much more than create Pods based on their `template` field. That template, though, is a full Pod spec, and that's available in the `spec.jobTemplate.spec.template.spec` field. I haven't tested it, but I don't see any reason the `affinity` field we've already got in our housekeeping CronJob template wouldn't work.

**Comment by Atoms** [comment]
ok, my bad, i saw error about that affinity when tried on cronjob, but that was cause of spacing wrong in definition.

**Comment by miso231** [comment]
@Atoms is right about the spacing in affinity definition. It should be `nindent 12` instead of `nindent 8` 

There 3 lines need to be fixed. Should I open a PR?
https://github.com/bootc/netbox-chart/blob/master/templates/cronjob.yaml#L161
https://github.com/bootc/netbox-chart/blob/master/templates/cronjob.yaml#L165
https://github.com/bootc/netbox-chart/blob/master/templates/cronjob.yaml#L169

**Comment by bootc** [comment]
Oh d'oh. Yes please, a PR would be really handy, thanks.

**Comment by anubisg1** [comment]
i would like to revive this as it still exists... this is what i have:

```
admin@azure-box:~/Netbox/internal$ kubectl get pods -n netbox
NAME                                 READY   STATUS              RESTARTS   AGE
netbox-64d9d994c5-g44rg              1/1     Running             0          2d22h
netbox-housekeeping-27450720-ktlgb   0/1     ContainerCreating   0          2d10h
netbox-postgresql-0                  1/1     Running             0          2d22h
netbox-redis-master-0                1/1     Running             0          2d22h
netbox-redis-replicas-0              1/1     Running             0          2d22h
netbox-redis-replicas-1              1/1     Running             0          2d22h
netbox-redis-replicas-2              1/1     Running             0          2d22h
netbox-worker-5b74cfd4-rnxqk         1/1     Running             2          2d22h
```

and this is the describe


```
sadmin@azure-box:~/Netbox/internal$ kubectl describe pod netbox-housekeeping-27450720-ktlgb -n netbox
Name:           netbox-housekeeping-27450720-ktlgb
Namespace:      netbox
Priority:       0
Node:           aks-nodepool1-27323697-vmss00000c/172.19.128.7
Start Time:     Sat, 12 Mar 2022 00:00:00 +0000
Labels:         app.kubernetes.io/component=housekeeping
                app.kubernetes.io/instance=netbox
                app.kubernetes.io/name=netbox
                controller-uid=7f27bfeb-a813-4065-aa83-4921e34e0b23
                job-name=netbox-housekeeping-27450720
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Job/netbox-housekeeping-27450720
Containers:
  netbox-housekeeping:
    Container ID:  
    Image:         netboxcommunity/netbox:v3.0.11
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/netbox/venv/bin/python
      /opt/netbox/netbox/manage.py
      housekeeping
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/netbox/config/configuration.py from config (ro,path="configuration.py")
      /opt/netbox/netbox/media from media (rw)
      /run/config/netbox from config (ro)
      /run/secrets/netbox from secrets (ro)
      /tmp from netbox-tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-chp5t (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      netbox
    Optional:  false
  secrets:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          netbox
    SecretOptionalName:  <nil>
    SecretName:          netbox-postgresql
    SecretOptionalName:  <nil>
    SecretName:          netbox-redis
    SecretOptionalName:  <nil>
    SecretName:          netbox-redis
    SecretOptionalName:  <nil>
  netbox-tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  media:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  netbox-media
    ReadOnly:   false
  kube-api-access-chp5t:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                      From     Message
  ----     ------       ----                     ----     -------
  Warning  FailedMount  58m (x248 over 2d10h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[media], unattached volumes=[secrets netbox-tmp media kube-api-access-chp5t config]: timed out waiting for the condition
  Warning  FailedMount  22m (x483 over 2d10h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[media], unattached volumes=[config secrets netbox-tmp media kube-api-access-chp5t]: timed out waiting for the condition
  Warning  FailedMount  17m (x260 over 2d10h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[media], unattached volumes=[netbox-tmp media kube-api-access-chp5t config secrets]: timed out waiting for the condition
  Warning  FailedMount  12m (x268 over 2d10h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[media], unattached volumes=[kube-api-access-chp5t config secrets netbox-tmp media]: timed out waiting for the condition
  Warning  FailedMount  3m46s (x277 over 2d10h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[media], unattached volumes=[media kube-api-access-chp5t config secrets netbox-tmp]: timed out waiting for the condition
```

**Comment by anubisg1** [comment]
additional information,  if i added podaffinity under "netbox-housekeeping" ,  that cannot be used.

here is values.yml extract

```
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 50
         podAffinityTerm:
           labelSelector:
             matchExpressions:
             - key: app.kubernetes.io/component
               operator: In
               values:
                 - netbox
           topologyKey: "kubernetes.io/hostname"
```


but that cannot be applied: `Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template): unknown field "podAffinity" in io.k8s.api.core.v1.PodTemplateSpec`

**Comment by adamrushuk** [comment]
> did you need netbox and the worker to be on the same node?

yes, as they share a common volume. I expect this will be the case with the `netbox-housekeeping` pod too.

Looking at the code, the component label is `housekeeping`: https://github.com/bootc/netbox-chart/blob/master/templates/cronjob.yaml#L16

so try this in your `values.yaml`:

```yaml
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/component
          operator: In
          values:
          - housekeeping
          - netbox

housekeeping:          
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
            - housekeeping
            - netbox
```
