### ISSUE TITLE
Question - Google Oauth2

### ISSUE THREAD

**Issue by qdupuy** [bootc/netbox-chart#79]
Hello, 🖖 

Has anyone managed to implement oauth with Google authentication from the helm charts ?

**Comment by bootc** [comment]
There's been some [interesting discussion](https://netdev-community.slack.com/archives/C01Q6B100R2/p1641819127001600) about this in Slack that you've been involved in; I'm leaving this here in case anyone comes along with the same question in future.

It would be really nice to have some more concrete, working examples of oauth2 implementations via the chart in some example values files, though.

**Comment by Atoms** [comment]
Yes, I managed to get it working :) 

```
remoteAuth:
  enabled: true
  backend: social_core.backends.google.GoogleOAuth2
```
```
extraConfig:
  social:
    values: 
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: '<key from app>.apps.googleusercontent.com'
      SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE: ["https://www.googleapis.com/auth/userinfo.email","https://www.googleapis.com/auth/userinfo.profile"]
  social-secret:
    secret:
      secretName: netbox-oauth2-secret
      items:
        - key: oauth2_secret.yaml
          path: oauth2_secret.yaml
```
and then secret:
```
data:
  oauth2_secret.yaml: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "XXXXXXXXXXXXXXXXXXXXXX"
```
don't forget to base64 encode all oauth2_secret.yaml in secret, it should look like:
``````
data:
  oauth2_secret.yaml: U09DSUFMX0FVVEhfR09PR0xFX09BVVRIMl9TRUNSRVQ6ICJYWFhYWFhYWFhYWFhYWFhYWFhYWFhYIg==
```
