### ISSUE TITLE
Issue when using sentinels

### ISSUE THREAD

**Issue by ccaillet1974** [bootc/netbox-chart#82]
Hi,

When I try to deploy netbox when using sentinels on my own redis deployment i've the following issue on pods : 
 "AttributeError: 'dict' object has no attribute 'split'

My deployment for redis is the chart from Bitnami with 3 statefulset sh-redis-ebs-node-0 to sh-redis-ebs-node-2, I've svc on my namespace : sh-redis-ebs which listens on port 6379 and 26379 for sentinel

I've tried to declare sentinels like that : 
```yaml
tasksRedis:
  database: 0
  ssl: false
  insecureSkipTlsVerify: false

  host: sh-redis-ebs.kube-dbs.svc.cluster.local
  port: 6379
  sentinels:
    - sh-redis-ebs-node-0: 26379
    - sh-redis-ebs-node-1: 26379
    - sh-redis-ebs-node-2: 26379
  sentinelService: sh-redis-ebs
  sentinelTimeout: 300
  password: <my_password>
```

Same declaration for cachingRedis

And when I use host and port instead of sentinel declaration my netbox pod seems to be ok but the worker is not and have some messages on logs that it wants to write on a read-only instance of redis

Could you help me to debug or give some direction to fix my issue ?

Thanks by advance for your reply

**Comment by bootc** [comment]
This is what I do for my configuration:
```yaml
tasksRedis:
  database: 1
  sentinels:
    - netbox-redis-ha-announce-0:26379
    - netbox-redis-ha-announce-1:26379
    - netbox-redis-ha-announce-2:26379
  sentinelTimeout: 3
  existingSecretName: netbox-redis
  existingSecretKey: redis-password
```
The main difference in mine is there is no space between the colon and the port number, e.g. you should use `sh-redis-ebs-node-0:26379`. This keeps that line as a string containing the host and port separated by a colon, as opposed to becoming a YAML mapping, which translates to a Python dict object. This dict object lacks the `split` method which the conf uses to split the string up into host and port number.
