### ISSUE TITLE
LDAP config not working

### ISSUE THREAD

**Issue by stblassitude** [bootc/netbox-chart#86]
I'm trying to enable LDAP against AD, but I seem to be missing something.

I have this in my values.yaml:
```
remoteAuth:
  enabled: true
  backend: netbox.authentication.LDAPBackend
  ldap:
    serverUri: 'ldap://dc1.example.com'
    startTls: false
    ignoreCertErrors: true
    bindDn: 'cn=netboxbind,ou=service accounts,DC=example,dc=com'
    bindPassword: 'geheim'
    userDnTemplate: null
    userSearchBaseDn: 'OU=Users,DC=example,dc=com'
    userSearchAttr: 'sAMAccountName'
    groupSearchBaseDn: 'OU=Groups,DC= example,dc=com'
    groupSearchClass: 'group'
    groupType: 'GroupOfNamesType'
    requireGroupDn: ''
    findGroupPerms: true
    mirrorGroups: true
    mirrorGroupsExcept: null
    cacheTimeout: 3600
    isAdminDn: 'CN=Network Configuration Operators,CN=Builtin,DC=example,dc=com'
    isSuperUserDn: 'CN=Domain Admins,CN=Users,DC=example,dc=com'
    attrFirstName: 'givenName'
    attrLastName: 'sn'
    attrMail: 'mail'
```

When I look at the chart, in particular configmap.yaml and running pod, the ldap.yaml is not mounted, but that's the only location that contains userSearchBaseDn, among other properties.

I think I followed the instructions in the README to the letter.
