### ISSUE TITLE
imagePullSecret

### ISSUE THREAD

**Issue by ludvik78** [bootc/netbox-chart#93]
When trying to pull my private docker repo I get 

"Error: YAML parse error on netbox/templates/cronjob.yaml: error converting YAML to JSON: yaml: line 34: did not find expected key"

I have this in my values.yml file
```
image:
  #repository: netboxcommunity/netbox
  repository: registry.gitlab.xxx.xx/xxx/xxxxxxxxxr/xxxxx/xxxxxxx/kubernetes/netbox/netbox
  pullPolicy: IfNotPresent
  #tag: "v2.11.10-ldap"
  tag: latest
imagePullSecrets:
  - name: regcred
```
